[build]
builder = "NIXPACKS"
nixpacksPlan = {"repo":"Fuzznip/stabiliserver"}

[deploy]
numReplicas = 1
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
command = "waitress-serve --host 0.0.0.0 --port $PORT main:app"
