from fastapi import APIRouter
from utils.trigger_dictionary import get_whitelist_data

router = APIRouter()

@router.get("/dink")
async def handle_request():
    whitelistData = get_whitelist_data()
    # Convert the drop dictionary into a list of item names
    # We can do this by looping through each item of the drop dictionary and adding the first index of the tuple to a list
    itemsList = []
    for (drop, _) in whitelistData.triggerDictionary:
        itemsList.append(drop)

    # Get the list of chat patterns as well
    chatPatterns = []
    for (filter, _) in whitelistData.messageFilters.items():
        chatPatterns.append(f"*{filter}*")

    return {
        "killCountInterval": 1,
        "combatTaskEnabled": True,
        "gambleRareNotifMessage": "",
        "speedrunEnabled": False,
        "questEnabled": True,
        "deathNotifMessage": "",
        "collectionNotifMessage": "",
        "levelNotifyVirtual": True,
        "questNotifMessage": "",
        "killCountEnabled": True,
        "slayerNotifMessage": "",
        "levelInterval": 1,
        "notifyTrades": False,
        "speedrunMessage": "",
        "sendDiscordUser": True,
        "clueSendImage": True,
        "chatNotifyMessage": "",
        "slayerEnabled": True,
        "deathEnabled": True,
        "combatTaskUnlockMessage": "",
        "deathMinValue": 0,
        "lootIncludeClueScrolls": True,
        "pkIncludeLocation": True,
        "lootIcons": False,
        "lootEnabled": True,
        "petNotifMessage": "",
        "nameFilterMode": "DENY",
        "lootRarityThreshold": 0,
        "maxRetries": 3,
        "speedrunPBOnly": False,
        "embedFooterText": "",
        "includeLocation": True,
        "groupStorageNotifyMessage": "",
        "deathEmbedProtected": False,
        "diarySendImage": True,
        "questSendImage": True,
        "killCountSendImage": True,
        "sendGroupIronClanName": True,
        "speedrunSendImage": False,
        "lootRarityValueIntersection": False,
        "levelEnabled": True,
        "petEnabled": True,
        "chatMessageTypes": [
            "GAME"
        ],
        "tradeMinValue": 0,
        "externalSendImage": "REQUESTED",
        "slayerPointThreshold": 10,
        "lootItemAllowlist": "\n".join(itemsList) if itemsList else "",
        "petSendImage": True,
        "groupStorageMinValue": 0,
        "embedFooterIcon": "",
        "killCountInitial": True,
        "combatTaskSendImage": True,
        "lootSendImage": True,
        "pkSendImage": True,
        "deathNotifPvpEnabled": True,
        "gambleInterval": 100,
        "combatTaskMessage": "",
        "notifyExternal": False,
        "collectionLogEnabled": True,
        "grandExchangeSendImage": True,
        "speedrunPBMessage": "",
        "deathSendImage": True,
        "lootImageMinValue": 0,
        "diaryMinDifficulty": "EASY",
        "clueMinTier": "BEGINNER",
        "pkNotifyMessage": "",
        "killCountPenanceQueen": True,
        "baseRetryDelay": 2000,
        "clueImageMinValue": 0,
        "lootIncludeGambles": False,
        "deathIgnoreSafe": True,
        "levelMinValue": 1,
        "includeClientFrame": False,
        "levelIntervalOverride": 0,
        "grandExchangeProgressSpacingMinutes": -1,
        "gambleSendImage": True,
        "pkEnabled": True,
        "imageWriteTimeout": 30,
        "gambleNotifMessage": "",
        "clueNotifMessage": "",
        "gambleRareLoot": True,
        "clueEnabled": True,
        "clueMinValue": 0,
        "levelSendImage": True,
        "embedColor": "#FFF40098",
        "chatPrivacy": "HIDE_NONE",
        "deathIgnoredRegions": "123, 456, 789",
        "chatSendImage": True,
        "groupStorageIncludeClan": True,
        "pkSkipSafe": True,
        "levelNotifyCombat": False,
        "sendClanName": True,
        "threadNameTemplate": "",
        "playerLookupService": "OSRS_HISCORE",
        "dynamicConfigUrl": "http://127.0.0.1:8000/dink",
        "discordWebhook": "http://127.0.0.1:8000/stability",
        "tradeNotifyMessage": "",
        "lootIncludePlayer": False,
        "combatTaskMinTier": "EASY",
        "grandExchangeIncludeCancelled": False,
        "seasonalPolicy": "ACCEPT",
        "deathSafeExceptions": [
            "FIGHT_CAVE",
            "INFERNO"
        ],
        "groupStorageSendImage": True,
        "levelNotifMessage": "",
        "killCountBestTimeMessage": "",
        "collectionSendImage": True,
        "screenshotScale": 100,
        "notifyChat": True,
        "lootNotifMessage": "",
        "chatPatterns": "\n".join(chatPatterns) if chatPatterns else "",
        "diaryEnabled": True,
        "deathNotifPvpMessage": "",
        "groupStorageEnabled": False,
        "diaryMessage": "",
        "minLootValue": 100000,
        "pkMinValue": 0,
        "notifyGrandExchange": False,
        "grandExchangeNotifyMessage": "",
        "killCountPB": True,
        "discordRichEmbeds": False,
        "slayerSendImage": True,
        "tradeSendImage": True,
        "grandExchangeMinValue": 100000,
        "xpInterval": 5,
        "clueShowItems": False,
        "killCountMessage": "",
        "groupStorageIncludePrice": True,
        "pkSkipFriendly": False,
        "lootRedirectPlayerKill": False,
        "gambleEnabled": True,
    }